guard/guard-rspec

lib/guard/rspec/runner.rb
lib/guard/rspec_formatter.rb

Guard crashes on my machine unless I insert this return statement.  Dunno if it's the right fix.
What's funny is that the bug seems to be introduced as a result of RuboCop?  https://github.com/guard/guard-rspec/commit/846ca4854ed290173ecd56d8a50ce255e7d9a598
Here's the crash:
```
07:43:32 - ERROR - Guard::RSpec failed to achieve its <run_all>, exception was:
> [#CD64AA63CA3A] NoMethodError: undefined method `match' for nil:NilClass
> [#CD64AA63CA3A] /Users/bronson/.gem/ruby/2.2.0/gems/guard-rspec-4.5.0/lib/guard/rspec/notifier.rb:32:in `_parse_summary'
> [#CD64AA63CA3A] /Users/bronson/.gem/ruby/2.2.0/gems/guard-rspec-4.5.0/lib/guard/rspec/notifier.rb:12:in `notify'
> [#CD64AA63CA3A] /Users/bronson/.gem/ruby/2.2.0/gems/guard-rspec-4.5.0/lib/guard/rspec/runner.rb:107:in …
```

fix crash by returning after notify_failure

---

lib/guard/rspec/runner.rb

In Ruby 2.x `File.exists?` was deprecated.

Fix `File.exists?` deprecation warning

---

lib/guard/rspec/results.rb
lib/guard/rspec/runner.rb
spec/lib/guard/rspec/command_spec.rb
spec/lib/guard/rspec/results_spec.rb
spec/lib/guard/rspec/runner_spec.rb
spec/lib/guard/rspec_spec.rb
spec/spec_helper.rb

- crash informatively when results file is invalid
- use instance_double to check mocks

improve results file handling

---

lib/guard/rspec/dsl.rb
spec/lib/guard/rspec/template_spec.rb
spec/spec_helper.rb

Since tools like `bundle gem` create the structure without lib,
Guard::RSpec should fall back to looking for files there too (fixes #322)

find spec/foo_spec.rb when no spec/lib/foo_spec.rb

---

lib/guard/rspec_formatter.rb
spec/lib/guard/rspec_formatter_spec.rb

RSpec 3 deprecates :example_group metadata key - this avoids the warning/error.
Also, metadata failures should are more detailed from now on.
[closes #327]

Avoid RSpec 3 deprecation warning [close #327]

---

README.md
lib/guard/rspec/rspec_process.rb
lib/guard/rspec/runner.rb
lib/guard/rspec_formatter.rb
spec/lib/guard/rspec/command_spec.rb
spec/lib/guard/rspec/rspec_process_spec.rb
spec/lib/guard/rspec/runner_spec.rb
spec/lib/guard/rspec_formatter_spec.rb

- new :result_file option to avoid issues with read-only dirs, etc.

Support custom result files

---

lib/guard/rspec/runner.rb
lib/guard/rspec_defaults.rb
lib/guard/rspec_formatter.rb
spec/lib/guard/rspec_formatter_spec.rb

Zeus doesn't pass environment variables, so Guard::RSpec can't
pass it's formatter file to the RSpec formatter through the environment.
This shows a warning (with url for info) and uses default results file instead.

rework Zeus env workaround [fix #326]

---

lib/guard/rspec/runner.rb
spec/lib/guard/rspec/runner_spec.rb

The refactoring in d4591fc broke throwing of `:task_has_failed` because the runner was changed to always return `true` from `#run` and `#run_all`. The invalid return value caused `:task_has_failed` to never be thrown, thus breaking the behavior of a group's `:halt_on_fail` option.

Fix return value of the runner

---

.travis.yml
lib/guard/rspec_formatter.rb
spec/lib/guard/rspec_formatter_spec.rb

Show an error so that users either simplify the RSpec glob pattern
(RSpec.configuration.pattern) or upgrade to a Ruby version supporting
FNM_EXTGLOB (fixes #338)

detect unsupported RSpec spec pattern

---

lib/guard/rspec/rspec_process.rb

When using guard-rspec and guard-process Guard::Process.wait2 method is called, which doesn't exists, the expected behaviour is to call Process.wait2 from ruby's stdlib, this happens due to a conflict in resolving Process constant which is evaluated against Guard.

Fixes guard-process collision

---

lib/guard/rspec/deprecator.rb
spec/lib/guard/rspec/deprecator_spec.rb

The default for failed_mode is :none, not :focus.
See 802edda29844df05ad6d7fe0f6304cc1ff855d9a

Fix deprecation message for focus_on_failed.

---

lib/guard/rspec/dsl.rb

Just noticed that the `rspec` and `rails` method used the `||=` operator and the `ruby` method didn't.

Added missing `=` to `||=` assignment operator.

---

guard-rspec.gemspec

When on the rubygems.org page for guard-rspec, clicking the homepage link would redirect to the same page, thus serving no purpose.
I propose to change the url to the github page, which has all the information that is required to use the gem.

Homepage URL

---

guard-rspec.gemspec
lib/guard/rspec.rb
lib/guard/rspec/options.rb
spec/lib/guard/rspec/notifier_spec.rb
spec/lib/guard/rspec_formatter_spec.rb

In a side project, using the following gem versions:
.gemspec:
```
...
gem.add_development_dependency('rspec', '~> 3.4.0')
gem.add_development_dependency('simplecov', '~> 0.7.0')
gem.add_development_dependency('guard', '~> 2.8.0')
gem.add_development_dependency('guard-rspec', '~> 4.6.4')
gem.add_development_dependency('rubocop', '~> 0.35.1')
gem.add_development_dependency('guard-rubocop', '~> 1.2.0')
gem.add_development_dependency('metric_fu', '~> 4.2.0')
gem.add_development_dependency('guard-reek', '~> 0.0.4')
gem.add_development_dependency('rake', '~> 10.4.2')
gem.add_development_dependency('yard', '~> 0.8.7')
gem.add_development_dependency('redcarpet', '~> 2.3.0')
```
Guardfile:
```
#
guard :rspec, cmd: 'bundle exec rspec', cli: '--tag ~slow' do
watch(%r{^spec/.+_spec\.rb}) …
```

Fixes 'NameError: uninitialized constant Guard::Guard::Compat'.

---

lib/guard/rspec_formatter.rb

Avoid using 'require' since guard-rspec is not on load path

use relative require in formatter [fix #352]

---

lib/guard/rspec_formatter.rb
spec/lib/guard/rspec_formatter_spec.rb

The value from `RSpec.configuration.pattern` may not satisfy a glob pattern
if multiple pattern is set (e.g. `'**{,/*/**}/*_spec.rb,**/*.feature'`).
And the formatter prints `no spec file location` warnings on STDOUT for each failed examples
because `spec_path?` method can't find the spec file location with a non-glob pattern.
This PR fixes `spec_path?` method to be able to find spec files even if a multiple pattern set.
The implementation is written referencing RSpec::Core::Configuration.
[rspec-core/configuration.rb at master · rspec/rspec-core · GitHub](https://github.com/rspec/rspec-core/blob/master/lib/rspec/core/configuration.rb#L1790)

Fix spec path verification with multiple pattern

---

.hound.yml
lib/guard/rspec/inspectors/focused_inspector.rb
lib/guard/rspec/options.rb
lib/guard/rspec/rspec_process.rb
lib/guard/rspec/runner.rb
lib/guard/rspec/version.rb
lib/guard/rspec_defaults.rb
lib/guard/rspec_formatter.rb
spec/lib/guard/rspec/inspectors/keeping_inspector_spec.rb
spec/lib/guard/rspec/results_spec.rb
spec/lib/guard/rspec/runner_spec.rb

Fixed to zero, so things are easier for other contributors.

fix all remaining rubocop offenses

---

lib/guard/rspec/rspec_process.rb
lib/guard/rspec/runner.rb
lib/guard/rspec_formatter.rb
spec/lib/guard/rspec/rspec_process_spec.rb
spec/lib/guard/rspec/runner_spec.rb

- warn about results file not being absolute
- misc diagnostic when Guard debug is active

add thorough warnings to help users report issues

---

lib/guard/rspec_formatter.rb
spec/acceptance/fixtures/succeeding_spec.rb
spec/acceptance/formatter_spec.rb
spec/spec_helper.rb

Formatter should be self-sufficient in that it shouldn't require
any gem or file other than what RSpec provides.

stop using Guard::UI in formatter + isolated test

---

README.md
lib/guard/rspec/options.rb
lib/guard/rspec/rspec_process.rb
lib/guard/rspec/runner.rb
spec/lib/guard/rspec/rspec_process_spec.rb
spec/lib/guard/rspec/runner_spec.rb

This is designed based on @e2's suggestion in #369. Bundler deprecated `with_clean_env` in 1.12.x and has stopped working for me. This adds the configuration of which method to use when executing the rspec cmd. The new default with be to use `with_original_env` based on the deprecation notice: https://github.com/bundler/bundler/blob/v1.12.5/lib/bundler.rb#L208 
I'm wondering if this should include an upgrade message for anyone bumping to this version.

add configuration of Bundler env, default to new behavior

---

README.md

Using the README's suggested `guard init rspec` command resulted in "Warning: you have a Gemfile, but you're not using bundler or RUBYGEMS_GEMDEPS"
[Guard's documentation ](https://github.com/guard/guard#installation)states "It's important that you always run Guard through Bundler to avoid errors."
[Similar issue on StackOverflow.](http://stackoverflow.com/questions/33052593/warning-regarding-not-using-bundler-when-running-guard-init)

update README from Guard documentation

---

lib/guard/rspec/rspec_process.rb
spec/lib/guard/rspec/rspec_process_spec.rb

Problem
---------
When exit code of RSpec is `nil`, `rspec-guard` crash.
`Process:Status#exitcode`  is likely to return a `nil`(e.g. segmentation fault). 
http://ruby-doc.org/core-2.3.0/Process/Status.html#method-i-exitstatus
Reproduce
-------
Sorry, I could not  create a minimal repro....
```
$ git clone https://github.com/pocke/rebirth
$ cd rebirth
$ git checkout a17a77c50a967f08999c1fc547ee59e59145df3c
$ bundle install
$ bundle exec guard
[1] guard(main)>  all
23:57:54 - ERROR - Guard::RSpec failed to achieve its <run_all>, exception was:
> [#f4335484be65] TypeError: can't convert nil into Integer
> [#f4335484be65] /home/pocke/.gem/ruby/2.3.0/gems/guard-rspec-4.7.2/lib/guard/rspec/rspec_process.rb:36:in `format'
> [#f4335484be65] …
```

Fix when RSpec exits by segmentation fault.

---

lib/guard/rspec/dsl.rb
lib/guard/rspec/templates/Guardfile

This will allow guard to watch something like `lib/task/foo.rake` and automatically run `spec/lib/tasks/foo_spec.rb` which is the standard locations for these in Rails

Add standard Rails rake task watcher
